from __future__ import annotations

from pathlib import Path

import svgwrite

from core.types import BackgroundMode, LayerResult, VectorPathData


def compose_svg_string(
    canvas_size: tuple[int, int],
    layers: list[LayerResult],
    title: str | None = None,
    background_mode: BackgroundMode = "transparent",
) -> str:
    width, height = canvas_size
    drawing = svgwrite.Drawing(
        size=(f"{width}px", f"{height}px"),
        viewBox=f"0 0 {width} {height}",
        profile="full",
    )
    drawing.attribs["version"] = "1.1"
    drawing.attribs["xmlns"] = "http://www.w3.org/2000/svg"

    drawing.set_desc(
        title=title or "AUTO VECTOR SABLON AI",
        desc="Generated by AUTO VECTOR SABLON AI",
    )

    if background_mode == "keep_white":
        drawing.add(drawing.rect(insert=(0, 0), size=(width, height), fill="#ffffff", stroke="none"))

    for layer in layers:
        group = drawing.g(
            id=f"layer-{layer.index}",
            fill=layer.hex_color,
            stroke="none",
            **{"fill-rule": "evenodd"},
        )
        for path_data in layer.svg_paths:
            path = drawing.path(d=path_data.d)
            if path_data.transform:
                path.update({"transform": path_data.transform})
            group.add(path)
        drawing.add(group)
    return drawing.tostring()


def export_svg_file(path: str | Path, svg_content: str) -> Path:
    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(svg_content, encoding="utf-8")
    return output


def compose_cutline_svg_string(
    canvas_size: tuple[int, int],
    cutline_paths: list[VectorPathData],
    title: str | None = None,
    stroke_color: str = "#ff00ff",
    stroke_width: float = 1.5,
) -> str:
    width, height = canvas_size
    drawing = svgwrite.Drawing(
        size=(f"{width}px", f"{height}px"),
        viewBox=f"0 0 {width} {height}",
        profile="full",
    )
    drawing.attribs["version"] = "1.1"
    drawing.attribs["xmlns"] = "http://www.w3.org/2000/svg"
    drawing.set_desc(
        title=title or "AUTO VECTOR SABLON AI Cutline",
        desc="Generated cutline by AUTO VECTOR SABLON AI",
    )

    group = drawing.g(
        id="cutline",
        fill="none",
        stroke=stroke_color,
        stroke_width=stroke_width,
        **{"stroke-linejoin": "round", "stroke-linecap": "round"},
    )
    for path_data in cutline_paths:
        path = drawing.path(d=path_data.d)
        if path_data.transform:
            path.update({"transform": path_data.transform})
        group.add(path)
    drawing.add(group)
    return drawing.tostring()
