from __future__ import annotations

import subprocess
import xml.etree.ElementTree as ET
from pathlib import Path

import cv2
import numpy as np

SVG_NS = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG_NS)


def _remove_small_regions(region: np.ndarray, minimum_area: int) -> np.ndarray:
    components, labels, stats, _ = cv2.connectedComponentsWithStats(region, connectivity=8)
    cleaned = np.zeros_like(region)

    for component_index in range(1, components):
        area = stats[component_index, cv2.CC_STAT_AREA]
        if area >= minimum_area:
            cleaned[labels == component_index] = 255

    return cleaned


def _trace_mask(mask_bitmap: np.ndarray, output_dir: Path, color_index: int, potrace_bin: str):
    bitmap_path = output_dir / f"mask-{color_index}.bmp"
    svg_path = output_dir / f"trace-{color_index}.svg"

    background = np.full(mask_bitmap.shape, 255, dtype=np.uint8)
    background[mask_bitmap > 0] = 0
    cv2.imwrite(str(bitmap_path), background)

    command = [
        potrace_bin,
        str(bitmap_path),
        "-s",
        "-o",
        str(svg_path),
        "-t",
        "8",
        "-a",
        "1.0",
        "-O",
        "0.25",
    ]

    subprocess.run(command, capture_output=True, text=True, check=True)
    return svg_path


def vectorize_bitmap(quantized, label_map, palette, output_svg_path: str | Path, potrace_bin: str = "potrace"):
    output_svg = Path(output_svg_path)
    work_dir = output_svg.parent / "traces"
    work_dir.mkdir(parents=True, exist_ok=True)

    minimum_area = max(int(label_map.shape[0] * label_map.shape[1] * 0.0002), 18)
    layers = []
    root_view_box = None

    for color in sorted(palette, key=lambda item: item["pixels"], reverse=True):
        color_index = color["index"]
        region = np.where(label_map == color_index, 255, 0).astype(np.uint8)
        region = _remove_small_regions(region, minimum_area)
        if cv2.countNonZero(region) == 0:
            continue

        svg_path = _trace_mask(region, work_dir, color_index, potrace_bin)
        svg_root = ET.parse(svg_path).getroot()
        if root_view_box is None:
            root_view_box = svg_root.get("viewBox")

        group = svg_root.find(f"{{{SVG_NS}}}g")
        if group is None:
            continue

        path_commands = []
        for node in group.findall(f"{{{SVG_NS}}}path"):
            command = node.get("d")
            if command:
                path_commands.append(command)

        if not path_commands:
            continue

        layers.append(
            {
                "fill": color["hex"],
                "transform": group.get("transform"),
                "paths": path_commands,
            }
        )

    if not layers:
        raise RuntimeError("Potrace did not produce any printable paths.")

    height, width = quantized.shape[:2]
    svg_root = ET.Element(
        f"{{{SVG_NS}}}svg",
        attrib={
            "version": "1.1",
            "viewBox": root_view_box or f"0 0 {width} {height}",
            "width": str(width),
            "height": str(height),
        },
    )
    description = ET.SubElement(svg_root, f"{{{SVG_NS}}}desc")
    description.text = "Generated by AI Screen Printing Vectorizer"

    for layer in layers:
        group_attributes = {
            "fill": layer["fill"],
            "stroke": "none",
            "fill-rule": "evenodd",
        }
        if layer["transform"]:
            group_attributes["transform"] = layer["transform"]

        group = ET.SubElement(svg_root, f"{{{SVG_NS}}}g", attrib=group_attributes)
        for command in layer["paths"]:
            ET.SubElement(group, f"{{{SVG_NS}}}path", attrib={"d": command})

    tree = ET.ElementTree(svg_root)
    ET.indent(tree, space="  ")
    tree.write(output_svg, encoding="utf-8", xml_declaration=True)

    return {
        "colorsTraced": len(layers),
        "minimumArea": int(minimum_area),
    }


def check_potrace(potrace_bin: str):
    try:
        completed = subprocess.run(
            [potrace_bin, "--version"],
            capture_output=True,
            text=True,
            check=True,
        )
        return {
            "available": True,
            "version": completed.stdout.strip() or completed.stderr.strip(),
        }
    except Exception as error:
        return {
            "available": False,
            "error": str(error),
        }

